=== bitsusei/TerraModulus-Gov/schemas/efp.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="efp">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metadata">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="obsoletedBy" minOccurs="0" type="efpList"/>
							<xs:element name="updatedBy" minOccurs="0" type="efpList"/>
							<xs:element name="derivedFrom" minOccurs="0" type="efpList"/>
							<xs:element name="obsoletes" minOccurs="0" type="efpList"/>
							<xs:element name="updates" minOccurs="0" type="efpList"/>
							<xs:element name="derives" minOccurs="0" type="efpList"/>
							<xs:element name="pullRequests">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="pullRequest" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="body">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="section" maxOccurs="unbounded"/>
							<xs:element name="namedReferences" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="reference" maxOccurs="unbounded">
											<xs:complexType>
												<xs:complexContent>
													<xs:extension base="reference">
														<xs:attribute name="anchor" type="xs:string">
															<xs:simpleType>
																<xs:restriction>
																	<xs:pattern value="[\w-]+"/>
																</xs:restriction>
															</xs:simpleType>
														</xs:attribute>
													</xs:extension>
												</xs:complexContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="references" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="reference" maxOccurs="unbounded">
											<xs:complexType>
												<xs:complexContent>
													<xs:extension base="reference">
														<xs:attribute name="id" type="xs:string"/>
													</xs:extension>
												</xs:complexContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="efp" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="title" type="xs:string" use="required">
				<xs:simpleType>
					<xs:restriction>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="created" type="xs:date" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="formal"/>
						<xs:enumeration value="informational"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="category" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="organization"/>
						<xs:enumeration value="project"/>
						<xs:enumeration value="governance"/>
						<xs:enumeration value="standard"/>
						<xs:enumeration value="general"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="status" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="draft"/>
						<xs:enumeration value="deferred"/>
						<xs:enumeration value="provisional"/>
						<xs:enumeration value="final"/>
						<xs:enumeration value="obsoleted"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="efpList">
		<xs:sequence>
			<xs:element name="efp" type="xs:positiveInteger" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="content" type="content" minOccurs="0"/>
				<xs:element ref="section" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="title" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="content" mixed="true">
		<xs:complexContent>
			<xs:extension base="xs:token">
				<xs:choice maxOccurs="unbounded" minOccurs="0">
					<!-- Some elements are referred from HTML and Writerside XML Markup -->
					<xs:element name="a">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="content">
									<xs:attribute name="href" type="xs:anyURI" use="required"/>
									<xs:attribute name="download" type="xs:string"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="code">
						<xs:complexType mixed="true">
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element name="i" type="content"/>
								<xs:element name="b" type="content"/>
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<xs:element name="code-block" type="xs:string">
						<xs:complexType mixed="true">
							<xs:attribute name="lang" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="br"/>
					<xs:element name="dl">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="li">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="content">
												<xs:attribute name="title" type="xs:string" use="required"/>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="i" type="content"/>
					<xs:element name="b" type="content"/>
					<xs:element name="u" type="content"/>
					<xs:element name="p" type="content"/>
					<xs:element name="img">
						<xs:complexType>
							<xs:attribute name="src" type="xs:anyURI" use="required"/>
							<xs:attribute name="alt" type="xs:string"/>
							<xs:attribute name="width" type="xs:string"/>
							<xs:attribute name="height" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="embed">
						<xs:complexType>
							<xs:attribute name="src" type="xs:anyURI" use="required"/>
							<xs:attribute name="width" type="xs:string"/>
							<xs:attribute name="height" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="list">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="li" type="content"/>
							</xs:sequence>
							<xs:attribute name="type" default="bullet">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="bullet"/>
										<xs:enumeration value="decimal"/>
										<xs:enumeration value="lower-alpha"/>
										<xs:enumeration value="none"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
					<xs:element ref="mathml:math" xmlns:mathml="http://www.w3.org/1998/Math/MathML"/>
					<xs:element name="kbd" type="xs:string"/>
					<xs:element name="table">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="tr" maxOccurs="unbounded">
									<xs:complexType>
										<xs:choice maxOccurs="unbounded">
											<xs:element name="th" type="content"/>
											<xs:element name="td" type="content"/>
										</xs:choice>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="tabs">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="tab" maxOccurs="unbounded">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="content">
												<xs:attribute name="title" type="xs:string" use="required"/>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="reference">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="author" type="xs:string"/>
			<xs:element name="date">
				<xs:complexType>
					<xs:attribute name="year" type="xs:gYear" use="required"/>
					<xs:attribute name="month" type="xs:gMonth"/>
					<xs:attribute name="day" type="xs:gDay"/>
					<xs:assert test="(not(@day) or @month)"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="seriesInfo">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="value" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="target" type="xs:anyURI"/>
	</xs:complexType>
</xs:schema>

=== bitsusei/TerraModulus-Gov/efp/2/main.xml
<?xml version="1.1" encoding="UTF-8" ?>
<efp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../../schemas/efp.xsd"
     efp="2" created="2026-05-13" type="formal" category="governance" status="draft"
     title="Proposal for Executive Policy Charter (EPC) Process">
	<metadata>
		<pullRequests>
			<pullRequest id="4"/>
		</pullRequests>
	</metadata>
	<body>
		<section title="Introduction">
			<content>
				<p>
					As established in the Constitution, Executive Policy Charters (EPCs) are executive-led, versioned,
					and policy-defining. They establish organizational principles, governance structures, and policies,
					but must always be initiated and guided by corresponding Execution Framework Proposals (EFPs).
				</p>
				<p>
					The latest iteration of an EPC may represent the current Policies, Rules and Regulations
					in the Constitution. It shall be a formal document with authoritative language.
					Any Members scoped from an EPC shall obey and have obligations to follow the Contents.
					Other than the basic Rules defined in the Constitution,
					this Proposal refines further for detailed steps and procedures for EPCs.
				</p>
			</content>
		</section>
	</body>
</efp>

=== bitsusei/TerraModulus-Gov/efp/1/main.xml
<?xml version="1.1" encoding="UTF-8" ?>
<efp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../../schemas/efp.xsd"
     efp="1" created="2026-05-12" type="formal" category="governance" status="draft"
     title="Proposal for Execution Framework Proposal (EFP) Process">
	<metadata>
		<pullRequests>
			<pullRequest id="3"/>
		</pullRequests>
	</metadata>
	<body>
		<section title="Introduction">
			<content>
				<p>
					As established in the Constitution, Execution Framework Proposals (EFPs) are community-driven,
					execution-defining, and immutable once finalized. They provide standards, methods,
					and structured execution plans, as well as records of executive procedures in the governance
					framework in the Constitution, like this Proposal.
				</p>
				<p>
					An approved EFP may represent the current state of affairs in the Constitution. It includes
					when certain procedures are being processed or certain proposals of ideas are created.
					An EFP may or may not take effects to change any aspects of affairs in the Constitution depending
					on the status of the said EFP. Other than the basic Rules defined in the Constitution, this
					Proposal refines further for detailed steps and procedures for EFPs.
				</p>
			</content>
		</section>
		<section title="Initiation of EFP">
			<content>
				<p>
					Any natural or artificial person as a participant in the Constitution should be able to initiate
					an EFP regardless of their positions and responsibilities, except when those participants are
					prohibited from participation in Governing Activities. Primary Roles of people should have been
					defined in the Constitution in advance for the participants in the Procedures.
				</p>
				<p>
					Once the identifier is assigned and the Pull Request of the Initiation is merged, the identifier
					is no longer free. It is possible that when the related parties have accepted before the creation
					of the Pull Request, the identifier is assigned in advance, so before closing the Pull Request,
					the identifier should still be reserved.
				</p>
			</content>
		</section>
		<section title="Structure of EFP Entries">
			<content>
				<p>
					The structures for an EFP should not be fixed for the contents, but the metadata.
					Besides, while contents other than the Contents are classified as Metadata, References are
					classified as Metadata even though they are shown aside the Contents in the Document Body.
				</p>
				<p>
					There should be no special restriction for what to be in the Contents, but probably later
					authoring guidelines for the Contents of EFPs may be introduced. This includes the References.
				</p>
				<p>
					The creation date should be the Coordinated Universal Time (UTC) date at the time the Document
					being created by the Author, however it is up to the Author's preference whenever the date is
					not after the UTC date the Pull Request is being created.
				</p>
				<p>
					Guidelines for how to use References should later be written for the suggestions of using them.
					Citation is recommended, but not necessary.
				</p>
			</content>
		</section>
		<section title="Structure of the Repository">
			<content>
				<p>
					The directory structure of the Repository should be explained in the words from the root directory.
				</p>
				<p>
					The directory names for the Entries may change if the naming rules of the identifiers change.
				</p>
				<p>
					The reserved idea of having more than one XML file in an Entry was to provide extra information
					like appendices, but so far there is no yet a use case, so it is still reserved.
				</p>
			</content>
		</section>
		<section title="Lifecycles of EFPs">
			<content>
				<p>
					Having "<b>Provisional</b>" status may be redundant when considering how EFPs are used.
					It stands for "Provisionally Adapted", comes from Python Enhancement Proposal (PEP).
					In general governance, having a temporarily adapted proposal while plans are mutable could be
					problematic in management, and thus fragile.
				</p>
				<p>
					"<b>Deferred</b>" EFPs may mean those EFPs are still incomplete, but not effective or used
					at the moment, so this status may be problematic if such EFPs are not properly handled.
				</p>
				<p>
					It is recommended to update the status system of EFPs by the above comments and concerns.
				</p>
			</content>
		</section>
		<section title="Classification">
			<content>
				<p>
					A guideline for clear boundaries between different contents for different aspects and categories
					should be suggested. When certain requirements are met, separate proposals should be made.
					Also, when certain standards or specifications could be generalized, such should be firstly made
					as <b>Standard</b> Proposals, then adapting proposals are to be made, for potential future reusing
					of standards or specifications in similar concepts, simplifying organizations of executions.
				</p>
				<p>
					Certain proposals like proposals of new standards and specifications may include examples, samples,
					or other formats of specifications as affiliated files in the Entries. They may be for reference or
					basic demonstration purposes.
				</p>
				<p>
					In the future, it is possible that when unified references to or dedicated management of standards are required.
					For such, it may be worth to consider whether there is a need to form a new System to govern
					all existing standards and specifications.
				</p>
				<p>
					At the moment, this Classification should well encompass all significant and effective proposals
					potentially present in the future. However, it is still possible for new Classification to occur;
					for such, the Constitution shall also be amended.
				</p>
			</content>
		</section>
		<section title="Amendment to Non-Finalized EFP Entries">
			<content>
				<p>
					Unlike usual Request For Comments (RFCs) on the Internet, minor changes to EFPs are quite easily
					tracked using a public Repository. Thus, it is kind of difficult to draw a line whether
					a Pull Request should be enough ready to be merged while being sufficient for public's references.
					Therefore, most likely when thematic changes are completed, such a Pull Request may be reviewed
					for merging, but the stage may be incomplete while there is no a true draft before official assignments.
					Unstable staging may exist due to the aforementioned reasons.
				</p>
			</content>
		</section>
		<section title="Amendment to Finalized EFP Entries">
			<content>
				<p>
					Unlike usual Request For Comments (RFCs) on the Internet, changes to EFPs may be tracked easily
					using a Version Control System (VCS). Thus, errata may be directly made as commits without
					having to specifically track them.
				</p>
				<p>
					Errata commits may describe the exact changes in the commit messages, while thematic changes may
					also be described in the corresponding Pull Requests. However, for minor changes, commit messages
					are more preferred than comments in Pull Requests.
				</p>
			</content>
		</section>
		<section title="Amendment to Formatting">
			<content>
				<p>
					Amendments to Formatting of Governance Documents may affect all the Document files in all the Entries,
					so an EFP should be introduced for the conduction of it.
				</p>
			</content>
		</section>
		<section title="See also">
			<content>
				<list>
					<li><a href="../efp001">EFP 1 (Constitution)</a></li>
				</list>
			</content>
		</section>
	</body>
</efp>
