=== bitsusei/TerraModulus-Gov/schemas/epc.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
	<xs:element name="epc">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="metadata">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="replacement" minOccurs="0" type="epcList"/>
							<xs:element name="proposal">
								<xs:complexType>
									<xs:attribute name="efp" type="xs:positiveInteger" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="body">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="preamble" type="content" minOccurs="0"/>
							<xs:element ref="section" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="sn" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="title" type="xs:string" use="required">
				<xs:simpleType>
					<xs:restriction>
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="created" type="xs:date" use="required"/>
			<xs:attribute name="version" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[1-9]\d*-[1-9]\d*"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="status" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="draft"/>
						<xs:enumeration value="deferred"/>
						<xs:enumeration value="provisional"/>
						<xs:enumeration value="active"/>
						<xs:enumeration value="deprecated"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="epcList">
		<xs:sequence>
			<xs:element name="epc" type="xs:positiveInteger" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="section">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="content" type="content" minOccurs="0"/>
				<xs:element ref="section" maxOccurs="unbounded" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="title" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="sectionContent"><!-- TBD -->
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="clause" type="content"/>
			<xs:element name="note" type="content"/>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="content" mixed="true">
		<xs:complexContent>
			<xs:extension base="xs:token">
				<xs:choice maxOccurs="unbounded" minOccurs="0">
					<!-- Some elements are referred from HTML and Writerside XML Markup -->
					<xs:element name="a">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="content">
									<xs:attribute name="href" type="xs:anyURI" use="required"/>
									<xs:attribute name="download" type="xs:string"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="code">
						<xs:complexType mixed="true">
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element name="i" type="content"/>
								<xs:element name="b" type="content"/>
							</xs:choice>
						</xs:complexType>
					</xs:element>
					<xs:element name="code-block" type="xs:string">
						<xs:complexType mixed="true">
							<xs:attribute name="lang" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="br"/>
					<xs:element name="dl">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="li">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="content">
												<xs:attribute name="title" type="xs:string" use="required"/>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="i" type="content"/>
					<xs:element name="b" type="content"/>
					<xs:element name="u" type="content"/>
					<xs:element name="p" type="content"/>
					<xs:element name="img">
						<xs:complexType>
							<xs:attribute name="src" type="xs:anyURI" use="required"/>
							<xs:attribute name="alt" type="xs:string"/>
							<xs:attribute name="width" type="xs:string"/>
							<xs:attribute name="height" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="embed">
						<xs:complexType>
							<xs:attribute name="src" type="xs:anyURI" use="required"/>
							<xs:attribute name="width" type="xs:string"/>
							<xs:attribute name="height" type="xs:string"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="list">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="li" type="content"/>
							</xs:sequence>
							<xs:attribute name="type" default="bullet">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="bullet"/>
										<xs:enumeration value="decimal"/>
										<xs:enumeration value="lower-alpha"/>
										<xs:enumeration value="none"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
					<xs:element ref="math:math" xmlns:math="http://www.w3.org/1998/Math/MathML"/>
					<xs:element name="kbd" type="xs:string"/>
					<xs:element name="table">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="tr" maxOccurs="unbounded">
									<xs:complexType>
										<xs:choice maxOccurs="unbounded">
											<xs:element name="th" type="content"/>
											<xs:element name="td" type="content"/>
										</xs:choice>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="tabs">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="tab" maxOccurs="unbounded">
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="content">
												<xs:attribute name="title" type="xs:string" use="required"/>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="reference">
		<xs:sequence>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="author" type="xs:string"/>
			<xs:element name="date">
				<xs:complexType>
					<xs:attribute name="year" type="xs:gYear" use="required"/>
					<xs:attribute name="month" type="xs:gMonth"/>
					<xs:attribute name="day" type="xs:gDay"/>
					<xs:assert test="(not(@day) or @month)"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="seriesInfo">
				<xs:complexType>
					<xs:attribute name="name" type="xs:string" use="required"/>
					<xs:attribute name="value" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="target" type="xs:anyURI"/>
	</xs:complexType>
</xs:schema>

=== bitsusei/TerraModulus-Gov/epc/2/1.xml
<?xml version="1.1" encoding="UTF-8" ?>
<epc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../../schemas/epc.xsd"
     sn="2" created="2026-05-13" version="2026-1" status="draft"
     title="Executive Policy Charter (EPC) Process">
	<metadata>
		<proposal efp="2"/>
	</metadata>
	<body>
		<section title="Filing">
			<content>
				<p>
					A full EPC identifier includes a serial number and a revision version string.
					EPC Streams shall be strictly sequential for the serial number,
					with the major version as the year of issue of an EPC version,
					and the minor version as the sequence of issue in an EPC stream in the year.
					An EPC Stream is a collection of all Versions for an EPC under the same serial number and title.
					Since EPCs are versioned, new versions of an EPC may override or supersede the older versions
					of the EPC series.
					However, a deprecation of an EPC may not lead to or be caused by another EPC.
				</p>
			</content>
		</section>
		<section title="Initiation of EPC">
			<content>
				<p>
					A Community Member may initiate an EPC via an EFP within a single Pull Request.
				</p>
				<p>
					When an EPC is being initiated, it must be in the status of "<b>Draft</b>".
				</p>
				<p>
					Identifiers for the EFP and EPC shall only be assigned when the Pull Request of the Initiation
					is accepted under consensus.
				</p>
			</content>
		</section>
		<section title="Structure of EPC Entries">
			<content>
				<p>
					Metadata and Contents of an EPC are separately regulated in different aspects.
				</p>
				<p>
					EPCs are managed and formatted using <b>Extensible Markup Language (XML)</b>.
					The formats of EPC Documents must be defined in an XML Schema stored in the Repository.
				</p>
			</content>
			<section title="Metadata">
				<content>
					<p>
						Metadata of an Entry include the title, the management information and references in Contents,
						where the management information includes the creation date and document status.
					</p>
					<p>
						The creation date should be the date on or before the date
						at the Coordinated Universal Time (UTC),
						the time the Document started being drafted by the Author.
					</p>
					<p>
						The title must not be empty, but the exact wording depends on the Author's preference under
						the consensus of the Document Moderators.
					</p>
					<p>
						References used must be in topic of the Document. The uses of named and unnamed References
						are separated, but the presence of them may be optional.
					</p>
				</content>
			</section>
			<section title="Contents">
				<content>
					<p>
						The Format of the Contents must align with the format of the XML defined in the XML Schema.
					</p>
					<p>
						Preamble is optional, where the present depends on intention of the Author;
						the Preamble shall be purely advisory and non-normative, as a brief abstract about the EPC.
					</p>
				</content>
			</section>
		</section>
		<section title="Structure of the Repository">
			<content>
				<p>
					All EPC Entries are stored in a directory named <code>epc</code> in the root.
					Each EPC Stream in the directory should be stored with its own subdirectory named
					with a single decimal number as the assigned serial number of the Stream.
				</p>
				<p>
					All the affiliated files and the XML Documents of the EPC itself should be stored in its directory
					for its Stream. The main XML Documents shall be stored as a file named <code><i>N</i>.xml</code>
					in the Stream directory, with <code>N</code> the sequential number of the Version in the Stream.
				</p>
				<p>
					The XML Schema is defined in <code>epc.xsd</code> in a root directory named <code>schemas</code>.
				</p>
			</content>
		</section>
		<section title="Lifecycles of EPCs">
			<content>
				<p>
					The status of an EPC Entry must be aligned with the status of its Proposal.
				</p>
				<p>
					A new iteration of Version of an EPC Stream shall be made only when the latest Version
					is "<b>Active</b>"; otherwise, modifications shall be made to the latest Version.
				</p>
				<p>
					When EPCs are firstly created, they are in the status of "<b>Draft</b>".
				</p>
				<p>
					If an EPC may be effective, it may turn into the status of "<b>Provisional</b>" while the Contents
					are still mutable.
					Once EPCs became "<b>Provisional</b>", they may not turn back to "<b>Draft</b>" by any mean.
				</p>
				<p>
					After reviewing and revisions, an EPC may become "<b>Active</b>" as finalized, and thus immutable.
					This means such EPC Entry is confirmed under the consensus of associated parties.
				</p>
				<p>
					Further revisions and changes regarding the concerning finalized EPC Entry should be conducted
					by proposing new Version of the EPC updating the latest Version, or new EPC Stream instead.
				</p>
				<p>
					A "<b>Draft</b>" or "<b>Provisional</b>" EFP may be "<b>Deferred</b>" when it is paused and its
					development may be postponed until future evaluation for continuation.
					Even if an EPC is logically "canceled",
					it would still be assigned to this status but with the implied meaning of being
					"indefinitely deferred".
					This would allow potential pick up of the EPC. If there is a replacement EPC,
					the EPC could be marked as "<b>Deprecated</b>" by the other EPC.
				</p>
			</content>
		</section>
		<section title="Interactions between EPCs">
			<content>
				<p>
					When an initiation of an EPC Entry of a new EPC Stream replaces the presence or effectiveness
					of another EPC, such new EPC is described to supersede and <b>Deprecate</b> the past EPC.
					The target EPC is then <b>Deprecated</b> by the other EPC;
					the latest Version of the replaced EPC shall be marked as "<b>Deprecated</b>" by the new EPC Stream.
					In certain cases, an EPC Stream may be solely "<b>Deprecated</b>" without a <b>Deprecating</b> EPC
					Stream, by marking the latest Version of that EPC Stream as "<b>Deprecated</b>".
				</p>
			</content>
		</section>
		<section title="Amendment to EPC Entries">
			<content>
				<p>
					EPC Entries with a status other than "<b>Active</b>" may be changed in any way, without restriction,
					only when there is only a single Entry in the EPC Stream,
					but dedicated modifications to a particular EPC Entry and its EFP must be organized
					in a single Pull Request.
				</p>
				<p>
					When there are more than one Entries in the EPC Stream and the latest Entry is not "<b>Active</b>",
					only changes to the Contents and subtle and trivial changes to other Parts are allowed;
					the Titles must remain immutable and unchanged.
				</p>
				<p>
					For changes to "<b>Active</b>" EPC Entries, only changes to Metadata are allowed;
					subtle and trivial changes to non-latest Versions are preferred to be in new iterations.
				</p>
				<p>
					Subtle and trivial changes include errata, corrections of intended wordings and meanings.
					However, sentence structure is not recommended to be changed, and any change to
					organizations of paragraphs is prohibited.
				</p>
				<p>
					Unless necessary, a Pull Request shall, at most, only modify one EFP Entry and one EPC Entry.
				</p>
			</content>
		</section>
		<section title="Document Rendering and Utilities">
			<content>
				<p>
					Rendering of EFPs should be done by generating Extensible HyperText Markup Language (XHTML) format
					according to the XML contents of the Documents.
					The resultant files are to be deployed to a static site.
					Those generated files should not be tracked by the Version Control System (VCS).
				</p>
				<p>
					Assistant or helper scripts or tools may be introduced for developers' or authors' convenience.
				</p>
			</content>
		</section>
		<section title="Management of Pull Requests">
			<content>
				<p>
					All Pull Requests regarding changes to EPC Entries are under regulation in the following clauses.
				</p>
				<p>
					When a Pull Request related to an initiation or modification to a particular EPC, its title
					must be prefixed with "[EPC <i>N</i>]" and a space, with the Rules of using identifiers,
					even the changes to its EFP are included in the Pull Request.
					Its Pull Request identifier number must be recorded in its EFP Document's Metadata.
				</p>
				<p>
					When a Pull Request only changes Metadata of EPCs without any changes to Contents, it may
					not be prefixed with an EPC identifier by the above clause.
				</p>
			</content>
		</section>
		<section title="Usage of Identifiers">
			<content>
				<p>
					Generally, when referring to a particular EPC, one may use "EPC <i>N</i>", where <i>N</i> is
					a positive integral identifier of the EPC without any leading zero;
					this syntax usually refers to the latest Version or the Version by the time this syntax is used.
				</p>
				<p>
					In the Repository, if there is any Issue or Discussion relates to any particular EPC,
					it may be mentioned in the titles by starting with "[EPC <i>N</i>]" by the above clause.
				</p>
				<p>
					If possible, the EPCs may also be linked in the article contents, by using
					<code>[EPC <i>N</i>](https://...)</code> (in Markdown) or
					<code>&lt;a href="https://..."&gt;EPC <i>N</i>&lt;/a&gt;</code> (in HTML), where
					the hyperlink address is the rendered webpage of the EPC.
				</p>
			</content>
		</section>
	</body>
</epc>
